name: CI pipeline

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install imagemagick lftp
      - name: Compress images
        run: find ./img/aufnahmeantrag/ -name '*' -exec mogrify -resize 1024x1024 -quality 100\> {} \;
        working-directory: ./src
      - name: Pull .well-known
        continue-on-error: true
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror .well-known ./; quit;" ${{ secrets.FTP_URL }}
        working-directory: ./src
      - name: Deploy new bundle
        run: lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror --reverse --delete --use-cache --verbose --allow-suid --no-umask --parallel=10; quit;" ${{ secrets.FTP_URL }}
        working-directory: ./src